# Source file directory
src: "./src"

# Build directory
out: "./out"

# Level directory
levels: "./levels"

# Level Options
options:
  - name: "Slider"
    scope: SomeScope
    type: slider
    def: 0.5
    min: 0
    max: 1
    step: 0.05
    display: percentage
  - name: "Toggle"
    type: toggle
    def: 0

# Judgement buckets (optional)
buckets:
  - sprites:
      - id: 1001
        x: 0
        y: 0
        w: 2
        h: 2
        rotation: 90
    windows:
      - min: -50
        max: 50
      - min: -100
        max: 100
      - min: -150
        max: 150